		ORG 0000H
		MOV R7, #255
		MOV R0, #02H
		MOV R2, #0
		MOV R3, #0
		MOV R4, #0
		MOV R5, #0
		MOV A, R7
LOOP:	MOV B, #10
		DIV AB
		MOV @R0, B
		INC R0
		CJNE A, #0, LOOP
		// DOAN CHUONG TRINH DUNG DE TACH CAC CHU SO VA LUU VAO CAC THANH GHI LAN LUOC R5 R4 R3 R2. VOI R2 LA HANG DON VI
LOOP1:	MOV DPTR, #0000H
		MOV A, #0E0H
		ADD A, R2
		MOVX @DPTR, A
		ACALL DELAY
		MOV A, #0D0H
		ADD A, R3
		MOVX @DPTR, A
		ACALL DELAY
		MOV A, #0B0H
		ADD A, R4
		MOVX @DPTR, A
		ACALL DELAY
		MOV A, #70H
		ADD A, R5
		MOVX @DPTR, A
		ACALL DELAY
		SJMP LOOP1
DELAY:	MOV R1, #10
LOOP2:	MOV R6, #100
		DJNZ R6, $
		DJNZ R1, LOOP2
		RET 
		END
		